### ISSUE TITLE
Problem change  mode from cdn to asset

### ISSUE THREAD

**Issue by hrace009** [andcarpi/laravel-popper#5]
Hello, i got problem when change mode from cdn to asset, and popper not showing.

![image](https://user-images.githubusercontent.com/7691118/159167081-439d00b4-27d1-421b-99dc-61af4bb48d92.png)

Can you help?

Thanks

**Comment by hrace009** [comment]
Hello, Any help?

**Comment by hrace009** [comment]
solve

**Comment by jayomayan** [comment]
Today the CDN went down for a few minutes and i tried top change the config to asset and having the same issue as above.. how did you fix this issue ? 
what is the correct path?

    'popper' => [
        'active' => true,
        'mode' => 'cdn',
        'cdn' => 'https://unpkg.com/popper.js@1',
        'asset' => 'vendor/laravel-popper/popper.min.js',
    ],
    'tippy' => [
        'active' => true,
        'mode' => 'cdn',
        'cdn' => 'https://unpkg.com/tippy.js@4',
        'asset' => 'vendor/laravel-popper/index.all.min.js',
    ],

**Comment by jayomayan** [comment]
@hrace009 how did you solve it?
